### ISSUE TITLE
CustomHTMLAnchorElement to-do

### ISSUE THREAD

**Issue by domenic** [domenic/html-as-custom-elements#37]
On top of #36, what else is needed?

API stuff:
- [ ] `.searchParams` (from `URLUtils`) doesn't work because it tries to "convert" to SearchParams. In general I think we should stop trying to convert unrecognized WebIDL types.
- [ ] `.ping` and `.relList` don't work because we can't reflect `DOMSettableTokenList` because we can't construct them. [Filed a bug on DOM, but unclear how to resolve it](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27114)
- [x] Need to make `.toString()` delegate to `.href` (i.e. implement "stringifier" functionality).

Styling stuff:
- [x] Styling in the UA stylesheet is not great, using `:-webkit-any-link` and other `-webkit-` things. [The spec's recommendations](https://html.spec.whatwg.org/multipage/rendering.html#phrasing-content-3) use `:link` and `:visited` which we don't have access to. Can hack around with something like `a[href]` to replace `:link` I suppose, but I wonder if that is actually equivalent? Is being able to be influenced by `:link` a custom elements gap?

Behavior!
- [x] Actually clicking on the link should navigate!
- [ ] Should respect `target`
- [ ] Should respect `ping`
- [ ] Should respect `download`!?
- [ ] Should be focusable: a big custom elements gap

Demo
- [x] Make it prettier
- [x] Provide an editable, updating-in-real-time view into all of the `CustomHTMLAnchorElement`'s properties
- [ ] Allow editing of the various DOM attributes
- [x] Put it on gh-pages

Tests
- [ ] There _have_ to be web-platform-tests for the URLUtils parts of the API, if nothing else.

**Comment by cvrebert** [comment]
- [ ] When right-clicking on a `<custom-a>`, the context menu lacks entries for link-specific actions (e.g. on OS X Chrome: "Save Link As…" and "Copy Link Address")
